language: python
virtualenv:
  system_site_packages: true
python:
  - "3.6"
  - "pypy3.5"
# command to install dependencies
install:
  - pip install .
  - pip install pytest-django
  - pip install django-cors-headers
  - pip install -r requirements.txt
script:
  - pytest


